using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class EmotionType
{
    public static string joy = "joy";
    public static string Love = "Love";
    public static string Optimism = "Optimism";
    public static string Admiration = "Admiration";
    public static string Gratitude = "Gratitude";
    public static string Desire = "Desire";
    public static string Sincerity = "Sincerity";
    public static string vitality = "vitality";
    public static string Trust = "Trust";
    public static string Acceptance = "Acceptance";
    public static string Harmony = "Harmony";
    public static string Serenity = "Serenity";
    public static string Calm = "Calm";
    public static string Boastfulness = "Boastfulness";
    public static string Pride = "Pride";
    public static string Angry = "Angry";
    public static string Bravery = "Bravery";
    public static string Defiance = "Defiance";
    public static string Contempt = "Contempt";
    public static string Deceptiveness = "Deceptiveness";
    public static string Hate = "Hate";
    public static string Aggressiveness = "Aggressiveness";
    public static string Disgust = "Disgust";
    public static string Insincerity = "Insincerity";
    public static string Annoyance = "Annoyance";
    public static string Envy = "Envy";
    public static string Suspicion = "Suspicion";
    public static string Pessimism = "Pessimism";
    public static string Disapproval = "Disapproval";
    public static string Conflict = "Conflict";
    public static string Insult = "Insult";
    public static string Sadness = "Sadness";
    public static string Fatigue = "Fatigue";
    public static string Neglect = "Neglect";
    public static string Tension = "Tension";
    public static string Passiveness = "Passiveness";
    public static string Boredom = "Boredom";
    public static string Distraction = "Distraction";
    public static string Apprehension = "Apprehension";
    public static string Uneasiness = "Uneasiness";
    public static string Remorse = "Remorse";
    public static string Submission = "Submission";
    public static string Grievance = "Grievance";
    public static string Shame = "Shame";
    public static string Depression = "Depression";
    public static string Fear = "Fear";
    public static string Embarrassed = "Embarrassed";
    public static string Puzzlement = "Puzzlement";
    public static string Cowardice = "Cowardice";
    public static string Awe = "Awe";
    public static string Surprise = "Surprise";
    public static string Anticipation = "Anticipation";
    public static string Interest = "Interest";
    public static string Neutra = "Neutra";

}
